name: Update Home H2

on:
  workflow_dispatch:
    inputs:
      heading:
        description: "H2 heading for home.ftl"
        required: true
        default: "Default Heading"

jobs:
  update-h2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update home.ftl H2
        run: |
          sed -i "s|<h2>.*</h2>|<h2>Java Demo Hi,${{ github.event.inputs.heading }}</h2>|" src/main/resources/templates/home.ftl

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Update home H2 to ${{ github.event.inputs.heading }}"
          git push
